model:
  name: Wav2Vec2
  pretrained: true
  

training:
  phase: 1
  epochs: 50
  batch_size: 32
  mixed_precision: true
 

optimizer_phase_1:
  name: AdamW
  learning_rate: 2e-4
  weight_decay: 1.0e-4
  betas: [0.9, 0.999]


scheduler_phase_1:
  mode: max
  patience: 3
  factor: 0.5

early_stopping_phase_1:
  patience: 6
  monitor: val_loss
# -----------------------------------------------------------------
training:
  phase: 2
  epochs: 50
  batch_size: 32
  mixed_precision: true

optimizer_phase_2:
  name: AdamW
  learning_rate: 1e-5
  weight_decay: 1.0e-4
  betas: [0.9, 0.999]


scheduler_phase_2:
  mode: max
  patience: 3
  factor: 0.5

early_stopping_phase_2:
  patience: 6
  monitor: val_loss  
  

data:
  sample_rate: 16kHz
  n_mels: 128
  input_type: mel_spectrogram
